var company_callsigns = [
['5K','Hi Fly'],
['AAL','American Airlines'],
['AAR','Asiana Airlines'],
['ABW','AirBridgeCargo Airlines'],
['ABX','ABX Air'],
['ABY','Air Arabia'],
['ACA','Air Canada'],
['ACI','Aircalin'],
['AEA','Air Europa'],
['AEE','Aegean Airlines'],
['AFL','Aeroflot'],
['AFR','Air France'],
['AFW','Africa World Airlines'],
['AHY','Azerbaijan Airlines'],
['AIC','Air India'],
['AIJ','Interjet'],
['AIZ','Arkia Israeli Airlines'],
['AJK','Allied Air'],
['ALK','SriLankan Airlines'],
['AMC','Air Malta'],
['AMU','Air Macau'],
['AMX','Aeromexico'],
['ANA','ANA'],
['ANE','Air Nostrum'],
['ANG','Air Niugini'],
['ANZ','Air New Zealand'],
['APK','Air Peace'],
['ARA','Arik Air'],
['ARE','LATAM Airlines Colombia'],
['ARG','Aerolineas Argentinas'],
['ASA','Alaska Airlines'],
['ASL','Air Serbia'],
['ATC','Air Tanzania'],
['AUA','Austrian'],
['AUI','Ukraine International Airlines'],
['AUL','Nordavia Regional Airlines'],
['AUT','Austral'],
['AVA','Avianca'],
['AVN','Air Vanuatu'],
['AZA','Alitalia'],
['AZG','Silk Way West Airlines'],
['AZP','Paranair'],
['AZU','Azul Brazilian Airlines'],
['BAV','Bamboo Airways'],
['BAW','British Airways'],
['BBC','Biman Bangladesh Airlines'],
['BCS','European Air Transport'],
['BCY','CityJet'],
['BEL','Brussels Airlines'],
['BHS','Bahamasair'],
['BKP','Bangkok Airways'],
['BMS','Blue Air'],
['BOT','Air Botswana'],
['BOV','BoA Boliviana de Aviacion'],
['BPA','Blue Panorama'],
['BRU','Belavia Belarusian Airlines'],
['BRX','Braathens Regional Airways'],
['BTI','Air Baltic'],
['BTK','Batik Air'],
['BWA','Caribbean Airlines'],
['CAI','Corendon Airlines'],
['CAL','China Airlines'],
['CBG','GX Airlines'],
['CBJ','Capital Airlines'],
['CCA','Air China'],
['CCM','Air Corsica'],
['CDC','Loong Air'],
['CDG','Shandong Airlines'],
['CEB','Cebu Pacific'],
['CES','China Eastern'],
['CFG','Condor'],
['CGA','Congo Airways'],
['CGH','Air Guilin'],
['CHB','West Air'],
['CHH','Hainan Airlines'],
['CJT','Cargojet Airways'],
['CKK','China Cargo Airlines'],
['CLH','Lufthansa CityLine'],
['CLX','Cargolux'],
['CMP','COPA Airlines'],
['CPA','Cathay Pacific'],
['CRC','Camair-Co'],
['CRK','Hong Kong Airlines'],
['CRL','Corsair International'],
['CSA','Czech Airlines'],
['CSC','Sichuan Airlines'],
['CSH','Shanghai Airlines'],
['CSN','China Southern Airlines'],
['CSS','SF Airlines'],
['CSZ','Shenzhen Airlines'],
['CTN','Croatia Airlines'],
['CUB','Cubana'],
['CUH','Urumqi Air'],
['CXA','Xiamen Airlines'],
['CYP','Cyprus Airways'],
['CYZ','China Postal Airlines'],
['DAH','Air Algérie'],
['DAL','Delta Air Lines'],
['DHK','DHL Air'],
['DHX','DHL Aviation'],
['DKH','Juneyao Airlines'],
['DLA','Air Dolomiti'],
['DLH','Lufthansa'],
['DTA','TAAG Angola Airlines'],
['DTH','Tassili Airlines'],
['EIN','Aer Lingus'],
['ELY','EL AL'],
['ETD','Etihad Airways'],
['ETH','Ethiopian Airlines'],
['EVA','EVA Air'],
['EVE','Evelop Airlines'],
['EWG','Eurowings'],
['EZE','Eastern Airways'],
['FBU','French Bee'],
['FDB','flydubai'],
['FDX','FedEx Express'],
['FEG','FlyEgypt'],
['FHY','Freebird Airlines'],
['FIN','Finnair'],
['FJI','Fiji Airways'],
['FLI','Atlantic Airways'],
['FPO','ASL Airlines France'],
['FWI','Air Caraibes'],
['FZA','Fuzhou Airlines'],
['GCR','Tianjin Airlines'],
['GEC','Lufthansa Cargo'],
['GFA','Gulf Air'],
['GIA','Garuda Indonesia'],
['GLG','Avianca Ecuador'],
['GLO','GOL Linhas Aereas'],
['GTI','Atlas Air'],
['HAL','Hawaiian Airlines'],
['HBH','Hebei Airlines'],
['HHN','Hahn Air'],
['HKC','Hong Kong Air Cargo'],
['HKE','Hong Kong Express Airways'],
['HVN','Vietnam Airlines'],
['HXA','China Express Airlines'],
['HYT','YTO Cargo Airlines'],
['IBB','Binter Canarias'],
['IBE','IBERIA'],
['ICE','Icelandair'],
['ICL','CAL Cargo Airlines'],
['IGO','IndiGo'],
['IQ','Qazaq Air'],
['IRA','Iran Air'],
['IRB','Iran Airtour Airline'],
['IRC','Iran Aseman Airlines'],
['IRM','Mahan Air'],
['ISR','Israir'],
['JAL','Japan Airlines'],
['JAV','Jordan Aviation'],
['JBU','JetBlue'],
['JJA','Jeju Air'],
['JNA','Jin Air'],
['JTA','Japan Transocean Air'],
['JZR','Jazeera Airways'],
['KAC','Kuwait Airways'],
['KAL','Korean Air'],
['KAR','Pegas Fly'],
['KHV','Cambodia Angkor Air'],
['KLM','KLM'],
['KMF','Kam Air'],
['KNA','Kunming Airlines'],
['KNE','Flynas'],
['KOR','Air Koryo'],
['KQA','Kenya Airways'],
['KRP','Carpatair'],
['KZR','Air Astana'],
['LAM','LAM'],
['LAN','LATAM Airlines Group'],
['LAO','Lao Airlines'],
['LAP','LATAM Airlines Paraguay'],
['LAV','Albastar'],
['LBT','Nouvelair'],
['LCO','LATAM Cargo Chile'],
['LGL','Luxair'],
['LIA','LIAT Airlines'],
['LKE','Lucky Air'],
['LMU','AlMasria Universal Airlines'],
['LNE','LATAM Airlines Ecuador'],
['LNK','Airlink'],
['LOT','LOT Polish Airlines'],
['LPE','LATAM Airlines Peru'],
['LRC','Avianca Costa Rica'],
['LTG','LATAM Cargo Brasil'],
['LZB','Bulgaria Air'],
['MAA','MasAir'],
['MAI','Mauritania Airlines International'],
['MAS','Malaysia Airlines'],
['MAU','Air Mauritius'],
['MDA','Mandarin Airlines'],
['MDG','Air Madagascar'],
['MEA','MEA'],
['MGL','MIAT Mongolian Airlines'],
['MGX','Montenegro Airlines'],
['MLD','Air Moldova'],
['MMA','Myanmar Airways International'],
['MMZ','EuroAtlantic Airways'],
['MNB','MNG Airlines'],
['MPH','Martinair Cargo'],
['MSA','Poste Air Cargo'],
['MSC','Air Cairo'],
['MSR','Egyptair'],
['MXD','Malindo Air'],
['NCA','NCA Nippon Cargo Airlines'],
['NIA','Nile Air'],
['NMA','Nesma Airlines'],
['NMB','Air Namibia'],
['NOS','Neos'],
['NWS','Nordwind Airlines'],
['OAL','Olympic Air'],
['OF','Overland Airways'],
['OHY','Onur Air'],
['OKA','Okay Airways'],
['OMA','Oman Air'],
['PAC','Polar Air Cargo'],
['PAL','Philippine Airlines'],
['PGA','PGA-Portugalia Airlines'],
['PGT','Pegasus Airlines'],
['PIA','PIA Pakistan International Airlines'],
['PLM','Wamos Air'],
['PRF','Precision Air'],
['PVG','Privilege Style'],
['QFA','Qantas'],
['QTR','Qatar Airways'],
['RAM','Royal Air Maroc'],
['RBA','Royal Brunei'],
['REU','Air Austral'],
['RIV','APG Airlines'],
['RJA','Royal Jordanian'],
['RLH','Ruili Airlines'],
['RLU','RusLine'],
['ROT','TAROM'],
['RPB','Aero Republica'],
['RWD','RwandAir'],
['RZO','Azores Airlines'],
['SAA','South African Airways'],
['SAS','SAS'],
['SAT','SATA  Air Acores'],
['SBI','S7 Airlines'],
['SDM','Rossiya Airlines'],
['SEJ','SpiceJet'],
['SEY','Air Seychelles'],
['SFR','Safair'],
['SGQ','SaudiGulf Airlines'],
['SIA','Singapore Airlines'],
['SKK','ASKY'],
['SKU','SKY Airline'],
['SLK','SilkAir'],
['SLM','Surinam Airways'],
['SMR','Somon Air'],
['SOL','Solomon Airlines'],
['SVA','Saudi Arabian Airlines'],
['SVR','Ural Airlines'],
['SWR','SWISS'],
['SXS','SunExpress'],
['SYR','Syrianair'],
['TAI','TACA'],
['TAM','LATAM Airlines Brasil'],
['TAO','Aeromar'],
['TAP','TAP Portugal'],
['TAR','Tunisair'],
['TCV','TACV Cabo Verde Airlines'],
['TGZ','Georgian Airways'],
['THA','Thai Airways International'],
['THD','Thai Smile'],
['THT','Air Tahiti Nui'],
['THY','Turkish Airlines'],
['TLM','Thai Lion Air'],
['TPC','Air Caledonie'],
['TSC','Air Transat'],
['TUI','TUIfly'],
['TWB','T’way Air'],
['TYA','NordStar'],
['UAE','Emirates'],
['UAL','United Airlines'],
['UIA','UNI AIR'],
['UPS','UPS Airlines'],
['UTA','UTair'],
['UZB','Uzbekistan Airways'],
['VBW','Air Burkina'],
['VIR','Virgin Atlantic'],
['VJC','Vietjet'],
['VLG','Vueling'],
['VOE','Volotea'],
['VOI','Volaris'],
['VOZ','Virgin Australia'],
['VSV','SCAT Airlines'],
['VTA','Air Tahiti'],
['VTI','Vistara'],
['WDL','German Airways'],
['WHT','White coloured by you'],
['WIF','Wideroe'],
['WJA','WestJet'],
['YZR','Suparna Airlines']];

function findCompany(callsign){
	var start = callsign.substring(0,3);
	for( i=0; i<company_callsigns.length; i++ ) {
		//console.log(company_callsigns[i]);
		if(company_callsigns[i][0] == start){
			//console.log(company_callsigns[i][1]); 
			return company_callsigns[i][1];
		}
	}
	return null; 
}
